services:
  - type: web
    name: mersenne-cpp-system
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    branch: main
    buildCommand: ""
    startCommand: "./mersenne_system"
    envVars:
      - key: PORT
        value: 8080
    healthCheckPath: /
    autoDeploy: true