services:
  - type: web
    name: mersenne-showcase
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
